In [1]:
import polars as pl
from medication_comorbidity_summary import summarize_medications_by_comorbidity

In [2]:
df = pl.read_parquet("final_patient_data.parquet")

In [3]:
df

shape: (10, 32)
┌────────────┬─────────┬────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ patient_id ┆ hosp_id ┆ centre ┆ hosp_admis ┆ … ┆ comorbidit ┆ hfrs_score ┆ OMT_compo ┆ death_fla │
│ ---        ┆ ---     ┆ ---    ┆ sion_datet ┆   ┆ y_score    ┆ ---        ┆ nent_scor ┆ g         │
│ str        ┆ i64     ┆ str    ┆ ime        ┆   ┆ ---        ┆ f64        ┆ e         ┆ ---       │
│            ┆         ┆        ┆ ---        ┆   ┆ f64        ┆            ┆ ---       ┆ i32       │
│            ┆         ┆        ┆ datetime[μ ┆   ┆            ┆            ┆ i8        ┆           │
│            ┆         ┆        ┆ s]         ┆   ┆            ┆            ┆           ┆           │
╞════════════╪═════════╪════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ P001       ┆ 1002    ┆ angers ┆ 2018-07-04 ┆ … ┆ 0.0        ┆ 0.0        ┆ 2         ┆ 1         │
│            ┆         ┆        ┆ 11:15:00   ┆   ┆            ┆            ┆           ┆           │
│ P002       ┆ 2002    ┆ brest  ┆ 2019-01-18 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0         ┆ 0         │
│            ┆         ┆        ┆ 13:20:00   ┆   ┆            ┆            ┆           ┆           │
│ P003       ┆ 3002    ┆ nantes ┆ 2019-04-09 ┆ … ┆ 3.0        ┆ 1.4        ┆ 2         ┆ 1         │
│            ┆         ┆        ┆ 09:15:00   ┆   ┆            ┆            ┆           ┆           │
│ P004       ┆ 4002    ┆ tours  ┆ 2018-03-03 ┆ … ┆ 0.0        ┆ 0.0        ┆ 1         ┆ 0         │
│            ┆         ┆        ┆ 07:50:00   ┆   ┆            ┆            ┆           ┆           │
│ P005       ┆ 5002    ┆ angers ┆ 2019-02-01 ┆ … ┆ 2.0        ┆ 0.0        ┆ 0         ┆ 1         │
│            ┆         ┆        ┆ 14:10:00   ┆   ┆            ┆            ┆           ┆           │
│ P006       ┆ 6002    ┆ brest  ┆ 2020-06-17 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0         ┆ 0         │
│            ┆         ┆        ┆ 10:45:00   ┆   ┆            ┆            ┆           ┆           │
│ P007       ┆ 7001    ┆ nantes ┆ 2020-07-22 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0         ┆ 0         │
│            ┆         ┆        ┆ 08:30:00   ┆   ┆            ┆            ┆           ┆           │
│ P008       ┆ 8002    ┆ tours  ┆ 2020-12-05 ┆ … ┆ 0.0        ┆ 3.7        ┆ 0         ┆ 1         │
│            ┆         ┆        ┆ 06:45:00   ┆   ┆            ┆            ┆           ┆           │
│ P009       ┆ 9002    ┆ angers ┆ 2017-01-26 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0         ┆ 0         │
│            ┆         ┆        ┆ 09:00:00   ┆   ┆            ┆            ┆           ┆           │
│ P010       ┆ 10002   ┆ brest  ┆ 2020-03-21 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0         ┆ 1         │
│            ┆         ┆        ┆ 16:30:00   ┆   ┆            ┆            ┆           ┆           │
└────────────┴─────────┴────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [4]:
comorbidity_cols = ["Cardiopathie ischémique", "Fibrillation atriale", "Insuffisance cardiaque chronique",
               "Pacemaker", "Pontage aorto-coronarien",  "Antécédent d'AVC"]

In [5]:
med_cols = ["beta_blocker", "ACEI", "ARB",  "anti_aldosterone",  "furosemide"]

In [6]:
summary_med_by_comorbidity = summarize_medications_by_comorbidity(
    df= df,
    disease_cols=comorbidity_cols,
    med_cols=med_cols
)

In [7]:
summary_med_by_comorbidity

shape: (6, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ Disease    ┆ Number of  ┆ Percent of ┆ Percent   ┆ Percent   ┆ Percent   ┆ Percent   ┆ Percent   │
│ ---        ┆ patients   ┆ all        ┆ taking    ┆ taking    ┆ taking    ┆ taking    ┆ taking    │
│ str        ┆ ---        ┆ patients   ┆ beta_bloc ┆ ACEI      ┆ ARB       ┆ anti_aldo ┆ furosemid │
│            ┆ i64        ┆ ---        ┆ ker       ┆ ---       ┆ ---       ┆ steron…   ┆ e         │
│            ┆            ┆ f64        ┆ ---       ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆ f64       ┆           ┆           ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Cardiopath ┆ 2          ┆ 20.0       ┆ 100.0     ┆ 50.0      ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ ie         ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ischémique ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Fibrillati ┆ 2          ┆ 20.0       ┆ 50.0      ┆ 50.0      ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ on atriale ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Insuffisan ┆ 1          ┆ 10.0       ┆ 100.0     ┆ 0.0       ┆ 0.0       ┆ 100.0     ┆ 100.0     │
│ ce         ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ cardiaque  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ chroniq…   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Pacemaker  ┆ 0          ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ Pontage    ┆ 0          ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ aorto-coro ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ narien     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Antécédent ┆ 1          ┆ 10.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ d'AVC      ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘