In [1]:
import polars as pl
from datetime import date

patient = pl.DataFrame({
    "patient_id": [
        "P001", "P002", "P003", "P004", "P005",
        "P006", "P007", "P008", "P009", "P010"
    ],
    "centre": [
        "angers", "brest", "nantes", "tours", "angers",
        "brest", "nantes", "tours", "angers", "brest"
    ],
    "gender": [
        "F", "M", "F", "M", "F",
        "M", "F", "M", "F", "M"
    ],
    "birth_date": [
        date(1933, 4, 12),
        date(1934, 11, 3),
        date(1935, 7, 26),
        date(1936, 2, 18),
        date(1937, 9, 9),
        date(1938, 12, 22),
        date(1939, 5, 15),
        date(1940, 1, 30),
        date(1933, 10, 5),
        date(1936, 6, 28),
    ],
    "internal_death_date": [
        date(2018, 9, 21),
        None,
        None,
        None,
        date(2019, 3, 17),
        None,
        None,
        None,
        None,
        date(2020, 4, 11),
    ],
    "external_death_date": [
        None,
        None,
        date(2020, 12, 4),
        None,
        None,
        None,
        None,
        date(2021, 7, 2),
        None,
        None,
    ],
    "last_seen_date": [
        date(2018, 9, 21),
        date(2021, 6, 14),
        date(2020, 12, 4),
        date(2021, 11, 30),
        date(2019, 3, 17),
        date(2021, 2, 8),
        date(2020, 8, 19),
        date(2021, 7, 2),
        date(2021, 12, 15),
        date(2020, 4, 11),
    ]
})

patient

shape: (10, 7)
┌────────────┬────────┬────────┬────────────┬──────────────────┬──────────────────┬────────────────┐
│ patient_id ┆ centre ┆ gender ┆ birth_date ┆ internal_death_d ┆ external_death_d ┆ last_seen_date │
│ ---        ┆ ---    ┆ ---    ┆ ---        ┆ ate              ┆ ate              ┆ ---            │
│ str        ┆ str    ┆ str    ┆ date       ┆ ---              ┆ ---              ┆ date           │
│            ┆        ┆        ┆            ┆ date             ┆ date             ┆                │
╞════════════╪════════╪════════╪════════════╪══════════════════╪══════════════════╪════════════════╡
│ P001       ┆ angers ┆ F      ┆ 1933-04-12 ┆ 2018-09-21       ┆ null             ┆ 2018-09-21     │
│ P002       ┆ brest  ┆ M      ┆ 1934-11-03 ┆ null             ┆ null             ┆ 2021-06-14     │
│ P003       ┆ nantes ┆ F      ┆ 1935-07-26 ┆ null             ┆ 2020-12-04       ┆ 2020-12-04     │
│ P004       ┆ tours  ┆ M      ┆ 1936-02-18 ┆ null             ┆ null             ┆ 2021-11-30     │
│ P005       ┆ angers ┆ F      ┆ 1937-09-09 ┆ 2019-03-17       ┆ null             ┆ 2019-03-17     │
│ P006       ┆ brest  ┆ M      ┆ 1938-12-22 ┆ null             ┆ null             ┆ 2021-02-08     │
│ P007       ┆ nantes ┆ F      ┆ 1939-05-15 ┆ null             ┆ null             ┆ 2020-08-19     │
│ P008       ┆ tours  ┆ M      ┆ 1940-01-30 ┆ null             ┆ 2021-07-02       ┆ 2021-07-02     │
│ P009       ┆ angers ┆ F      ┆ 1933-10-05 ┆ null             ┆ null             ┆ 2021-12-15     │
│ P010       ┆ brest  ┆ M      ┆ 1936-06-28 ┆ 2020-04-11       ┆ null             ┆ 2020-04-11     │
└────────────┴────────┴────────┴────────────┴──────────────────┴──────────────────┴────────────────┘

In [2]:
import polars as pl
from datetime import datetime

stay = pl.DataFrame({
    "patient_id": [
        "P001", "P001", "P001",
        "P002", "P002",
        "P003", "P003", "P003", "P003",
        "P004", "P004", "P004",
        "P005", "P005",
        "P006", "P006",
        "P007",
        "P008", "P008", "P008",
        "P009", "P009",
        "P010", "P010",
    ],

    "centre": [
        "angers", "angers", "angers",
        "brest", "brest",
        "nantes", "nantes", "nantes", "nantes",
        "tours", "tours", "tours",
        "angers", "angers",
        "brest", "brest",
        "nantes",
        "tours", "tours", "tours",
        "angers", "angers",
        "brest", "brest",
    ],

    "hosp_id": [
        1001, 1002, 1002,
        2001, 2002,
        3001, 3002, 3003, 3003,
        4001, 4002, 4002,
        5001, 5002,
        6001, 6002,
        7001,
        8001, 8002, 8002,
        9001, 9002,
        10001, 10002,
    ],

    "hosp_admission_datetime": [
        datetime(2015, 3, 10, 9, 30),
        datetime(2018, 7, 4, 11, 15),
        datetime(2018, 7, 4, 11, 15),

        datetime(2014, 6, 22, 8, 40),
        datetime(2019, 1, 18, 13, 20),

        datetime(2016, 2, 5, 10, 0),
        datetime(2019, 4, 9, 9, 15),
        datetime(2020, 10, 2, 12, 0),
        datetime(2020, 10, 2, 12, 0),

        datetime(2015, 11, 14, 15, 0),
        datetime(2018, 3, 3, 7, 50),
        datetime(2018, 3, 3, 7, 50),

        datetime(2016, 8, 19, 11, 0),
        datetime(2019, 2, 1, 14, 10),

        datetime(2017, 5, 6, 9, 20),
        datetime(2020, 6, 17, 10, 45),

        datetime(2020, 7, 22, 8, 30),

        datetime(2017, 9, 10, 13, 0),
        datetime(2020, 12, 5, 6, 45),
        datetime(2020, 12, 5, 6, 45),

        datetime(2014, 12, 3, 10, 15),
        datetime(2017, 1, 26, 9, 0),

        datetime(2015, 4, 18, 12, 20),
        datetime(2020, 3, 21, 16, 30),
    ],

    "hosp_discharge_datetime": [
        datetime(2015, 3, 16, 14, 0),
        datetime(2018, 7, 12, 10, 0),
        datetime(2018, 7, 12, 10, 0),

        datetime(2014, 6, 28, 15, 30),
        datetime(2019, 1, 25, 11, 0),

        datetime(2016, 2, 11, 16, 0),
        datetime(2019, 4, 18, 10, 30),
        datetime(2020, 10, 9, 9, 45),
        datetime(2020, 10, 9, 9, 45),

        datetime(2015, 11, 20, 13, 0),
        datetime(2018, 3, 18, 12, 20),
        datetime(2018, 3, 18, 12, 20),

        datetime(2016, 8, 24, 10, 0),
        datetime(2019, 2, 8, 15, 0),

        datetime(2017, 5, 12, 11, 30),
        datetime(2020, 6, 24, 12, 0),

        datetime(2020, 7, 29, 10, 15),

        datetime(2017, 9, 16, 9, 30),
        datetime(2020, 12, 20, 16, 0),
        datetime(2020, 12, 20, 16, 0),

        datetime(2014, 12, 9, 14, 20),
        datetime(2017, 2, 3, 11, 45),

        datetime(2015, 4, 23, 10, 0),
        datetime(2020, 4, 2, 9, 0),
    ],

    "stay_id": [
        1, 2, 3,
        4, 5,
        6, 7, 8, 9,
        10, 11, 12,
        13, 14,
        15, 16,
        17,
        18, 19, 20,
        21, 22,
        23, 24,
    ],

    # Numeric UF/unit codes
    # 101 = cardiologie
    # 102 = urgences
    # 103 = pneumologie
    # 104 = médecine interne
    # 105 = réanimation
    "unit_code": [
        101, 102, 103,
        104, 103,
        101, 103, 102, 104,
        101, 102, 105,
        104, 103,
        101, 103,
        103,
        104, 102, 105,
        101, 103,
        101, 103,
    ],

    "unit_admission_datetime": [
        datetime(2015, 3, 10, 9, 30),
        datetime(2018, 7, 4, 11, 15),
        datetime(2018, 7, 5, 10, 0),

        datetime(2014, 6, 22, 8, 40),
        datetime(2019, 1, 18, 13, 20),

        datetime(2016, 2, 5, 10, 0),
        datetime(2019, 4, 9, 9, 15),
        datetime(2020, 10, 2, 12, 0),
        datetime(2020, 10, 3, 9, 30),

        datetime(2015, 11, 14, 15, 0),
        datetime(2018, 3, 3, 7, 50),
        datetime(2018, 3, 4, 9, 0),

        datetime(2016, 8, 19, 11, 0),
        datetime(2019, 2, 1, 14, 10),

        datetime(2017, 5, 6, 9, 20),
        datetime(2020, 6, 17, 10, 45),

        datetime(2020, 7, 22, 8, 30),

        datetime(2017, 9, 10, 13, 0),
        datetime(2020, 12, 5, 6, 45),
        datetime(2020, 12, 6, 8, 30),

        datetime(2014, 12, 3, 10, 15),
        datetime(2017, 1, 26, 9, 0),

        datetime(2015, 4, 18, 12, 20),
        datetime(2020, 3, 21, 16, 30),
    ],

    "unit_discharge_datetime": [
        datetime(2015, 3, 16, 14, 0),
        datetime(2018, 7, 5, 10, 0),
        datetime(2018, 7, 12, 10, 0),

        datetime(2014, 6, 28, 15, 30),
        datetime(2019, 1, 25, 11, 0),

        datetime(2016, 2, 11, 16, 0),
        datetime(2019, 4, 18, 10, 30),
        datetime(2020, 10, 3, 9, 30),
        datetime(2020, 10, 9, 9, 45),

        datetime(2015, 11, 20, 13, 0),
        datetime(2018, 3, 4, 9, 0),
        datetime(2018, 3, 18, 12, 20),

        datetime(2016, 8, 24, 10, 0),
        datetime(2019, 2, 8, 15, 0),

        datetime(2017, 5, 12, 11, 30),
        datetime(2020, 6, 24, 12, 0),

        datetime(2020, 7, 29, 10, 15),

        datetime(2017, 9, 16, 9, 30),
        datetime(2020, 12, 6, 8, 30),
        datetime(2020, 12, 20, 16, 0),

        datetime(2014, 12, 9, 14, 20),
        datetime(2017, 2, 3, 11, 45),

        datetime(2015, 4, 23, 10, 0),
        datetime(2020, 4, 2, 9, 0),
    ],

    "inclusion_flag": [
        0, 1, 1,
        0, 1,
        0, 1, 1, 1,
        0, 1, 1,
        0, 1,
        0, 1,
        1,
        0, 1, 1,
        0, 1,
        0, 1,
    ],
})

stay

shape: (24, 10)
┌────────────┬────────┬─────────┬────────────┬───┬───────────┬────────────┬────────────┬───────────┐
│ patient_id ┆ centre ┆ hosp_id ┆ hosp_admis ┆ … ┆ unit_code ┆ unit_admis ┆ unit_disch ┆ inclusion │
│ ---        ┆ ---    ┆ ---     ┆ sion_datet ┆   ┆ ---       ┆ sion_datet ┆ arge_datet ┆ _flag     │
│ str        ┆ str    ┆ i64     ┆ ime        ┆   ┆ i64       ┆ ime        ┆ ime        ┆ ---       │
│            ┆        ┆         ┆ ---        ┆   ┆           ┆ ---        ┆ ---        ┆ i64       │
│            ┆        ┆         ┆ datetime[μ ┆   ┆           ┆ datetime[μ ┆ datetime[μ ┆           │
│            ┆        ┆         ┆ s]         ┆   ┆           ┆ s]         ┆ s]         ┆           │
╞════════════╪════════╪═════════╪════════════╪═══╪═══════════╪════════════╪════════════╪═══════════╡
│ P001       ┆ angers ┆ 1001    ┆ 2015-03-10 ┆ … ┆ 101       ┆ 2015-03-10 ┆ 2015-03-16 ┆ 0         │
│            ┆        ┆         ┆ 09:30:00   ┆   ┆           ┆ 09:30:00   ┆ 14:00:00   ┆           │
│ P001       ┆ angers ┆ 1002    ┆ 2018-07-04 ┆ … ┆ 102       ┆ 2018-07-04 ┆ 2018-07-05 ┆ 1         │
│            ┆        ┆         ┆ 11:15:00   ┆   ┆           ┆ 11:15:00   ┆ 10:00:00   ┆           │
│ P001       ┆ angers ┆ 1002    ┆ 2018-07-04 ┆ … ┆ 103       ┆ 2018-07-05 ┆ 2018-07-12 ┆ 1         │
│            ┆        ┆         ┆ 11:15:00   ┆   ┆           ┆ 10:00:00   ┆ 10:00:00   ┆           │
│ P002       ┆ brest  ┆ 2001    ┆ 2014-06-22 ┆ … ┆ 104       ┆ 2014-06-22 ┆ 2014-06-28 ┆ 0         │
│            ┆        ┆         ┆ 08:40:00   ┆   ┆           ┆ 08:40:00   ┆ 15:30:00   ┆           │
│ P002       ┆ brest  ┆ 2002    ┆ 2019-01-18 ┆ … ┆ 103       ┆ 2019-01-18 ┆ 2019-01-25 ┆ 1         │
│            ┆        ┆         ┆ 13:20:00   ┆   ┆           ┆ 13:20:00   ┆ 11:00:00   ┆           │
│ …          ┆ …      ┆ …       ┆ …          ┆ … ┆ …         ┆ …          ┆ …          ┆ …         │
│ P008       ┆ tours  ┆ 8002    ┆ 2020-12-05 ┆ … ┆ 105       ┆ 2020-12-06 ┆ 2020-12-20 ┆ 1         │
│            ┆        ┆         ┆ 06:45:00   ┆   ┆           ┆ 08:30:00   ┆ 16:00:00   ┆           │
│ P009       ┆ angers ┆ 9001    ┆ 2014-12-03 ┆ … ┆ 101       ┆ 2014-12-03 ┆ 2014-12-09 ┆ 0         │
│            ┆        ┆         ┆ 10:15:00   ┆   ┆           ┆ 10:15:00   ┆ 14:20:00   ┆           │
│ P009       ┆ angers ┆ 9002    ┆ 2017-01-26 ┆ … ┆ 103       ┆ 2017-01-26 ┆ 2017-02-03 ┆ 1         │
│            ┆        ┆         ┆ 09:00:00   ┆   ┆           ┆ 09:00:00   ┆ 11:45:00   ┆           │
│ P010       ┆ brest  ┆ 10001   ┆ 2015-04-18 ┆ … ┆ 101       ┆ 2015-04-18 ┆ 2015-04-23 ┆ 0         │
│            ┆        ┆         ┆ 12:20:00   ┆   ┆           ┆ 12:20:00   ┆ 10:00:00   ┆           │
│ P010       ┆ brest  ┆ 10002   ┆ 2020-03-21 ┆ … ┆ 103       ┆ 2020-03-21 ┆ 2020-04-02 ┆ 1         │
│            ┆        ┆         ┆ 16:30:00   ┆   ┆           ┆ 16:30:00   ┆ 09:00:00   ┆           │
└────────────┴────────┴─────────┴────────────┴───┴───────────┴────────────┴────────────┴───────────┘

In [3]:
import polars as pl

unit_mapping = pl.DataFrame({
    "centre": [
        "angers", "angers", "angers", "angers",
        "brest", "brest", "brest",
        "nantes", "nantes", "nantes", "nantes",
        "tours", "tours", "tours", "tours",
    ],

    "unit_code": [
        101, 102, 103, 104,
        101, 103, 104,
        101, 102, 103, 104,
        102, 104, 105, 101,
    ],

    "unit_name": [
        "Cardiologie - Angers",
        "Urgences - Angers",
        "Pneumologie - Angers",
        "Médecine interne - Angers",

        "Cardiologie - Brest",
        "Pneumologie - Brest",
        "Médecine interne - Brest",

        "Cardiologie - Nantes",
        "Urgences - Nantes",
        "Pneumologie - Nantes",
        "Médecine interne - Nantes",

        "Urgences - Tours",
        "Médecine interne - Tours",
        "Réanimation - Tours",
        "Cardiologie - Tours",
    ],

    "unit_group": [
        "cardiologie",
        "urgences",
        "pneumologie",
        "médecine interne",

        "cardiologie",
        "pneumologie",
        "médecine interne",

        "cardiologie",
        "urgences",
        "pneumologie",
        "médecine interne",

        "urgences",
        "médecine interne",
        "réanimation",
        "cardiologie",
    ],
})

unit_mapping

shape: (15, 4)
┌────────┬───────────┬───────────────────────────┬──────────────────┐
│ centre ┆ unit_code ┆ unit_name                 ┆ unit_group       │
│ ---    ┆ ---       ┆ ---                       ┆ ---              │
│ str    ┆ i64       ┆ str                       ┆ str              │
╞════════╪═══════════╪═══════════════════════════╪══════════════════╡
│ angers ┆ 101       ┆ Cardiologie - Angers      ┆ cardiologie      │
│ angers ┆ 102       ┆ Urgences - Angers         ┆ urgences         │
│ angers ┆ 103       ┆ Pneumologie - Angers      ┆ pneumologie      │
│ angers ┆ 104       ┆ Médecine interne - Angers ┆ médecine interne │
│ brest  ┆ 101       ┆ Cardiologie - Brest       ┆ cardiologie      │
│ …      ┆ …         ┆ …                         ┆ …                │
│ nantes ┆ 104       ┆ Médecine interne - Nantes ┆ médecine interne │
│ tours  ┆ 102       ┆ Urgences - Tours          ┆ urgences         │
│ tours  ┆ 104       ┆ Médecine interne - Tours  ┆ médecine interne │
│ tours  ┆ 105       ┆ Réanimation - Tours       ┆ réanimation      │
│ tours  ┆ 101       ┆ Cardiologie - Tours       ┆ cardiologie      │
└────────┴───────────┴───────────────────────────┴──────────────────┘

In [4]:
unit_mapping.filter

<bound method DataFrame.filter of shape: (15, 4)
┌────────┬───────────┬───────────────────────────┬──────────────────┐
│ centre ┆ unit_code ┆ unit_name                 ┆ unit_group       │
│ ---    ┆ ---       ┆ ---                       ┆ ---              │
│ str    ┆ i64       ┆ str                       ┆ str              │
╞════════╪═══════════╪═══════════════════════════╪══════════════════╡
│ angers ┆ 101       ┆ Cardiologie - Angers      ┆ cardiologie      │
│ angers ┆ 102       ┆ Urgences - Angers         ┆ urgences         │
│ angers ┆ 103       ┆ Pneumologie - Angers      ┆ pneumologie      │
│ angers ┆ 104       ┆ Médecine interne - Angers ┆ médecine interne │
│ brest  ┆ 101       ┆ Cardiologie - Brest       ┆ cardiologie      │
│ …      ┆ …         ┆ …                         ┆ …                │
│ nantes ┆ 104       ┆ Médecine interne - Nantes ┆ médecine interne │
│ tours  ┆ 102       ┆ Urgences - Tours          ┆ urgences         │
│ tours  ┆ 104       ┆ Médecine interne - Tours  ┆ médecine interne │
│ tours  ┆ 105       ┆ Réanimation - Tours       ┆ réanimation      │
│ tours  ┆ 101       ┆ Cardiologie - Tours       ┆ cardiologie      │
└────────┴───────────┴───────────────────────────┴──────────────────┘>

In [5]:
unit_mapping.select(pl.col("unit_code").n_unique())

shape: (1, 1)
┌───────────┐
│ unit_code │
│ ---       │
│ u32       │
╞═══════════╡
│ 5         │
└───────────┘

In [6]:


import polars as pl

unit_mapping = pl.DataFrame({
    "centre": [
        "angers", "angers", "angers", "angers",
        "brest", "brest", "brest",
        "nantes", "nantes", "nantes", "nantes",
        "tours", "tours", "tours", "tours",
    ],

    "unit_code": [
        101, 102, 103, 104,
        101, 103, 104,
        101, 102, 103, 104,
        101, 102, 104, 105,
    ],

    "unit_name": [
        "Cardiologie Angers",
        "Urgences Angers",
        "Pneumologie Angers",
        "Médecine interne Angers",

        "Cardiologie Brest",
        "Pneumologie Brest",
        "Médecine interne Brest",

        "Cardiologie Nantes",
        "Urgences Nantes",
        "Pneumologie Nantes",
        "Médecine interne Nantes",

        "Cardiologie Tours",
        "Urgences Tours",
        "Médecine interne Tours",
        "Réanimation médicale Tours",
    ],

    "unit_group": [
        "Cardiologie",
        "Urgences",
        "Pneumologie",
        "Médecine interne",

        "Cardiologie",
        "Pneumologie",
        "Médecine interne",

        "Cardiologie",
        "Urgences",
        "Pneumologie",
        "Médecine interne",

        "Cardiologie",
        "Urgences",
        "Médecine interne",
        "Réanimation",
    ],
})

unit_mapping

shape: (15, 4)
┌────────┬───────────┬────────────────────────────┬──────────────────┐
│ centre ┆ unit_code ┆ unit_name                  ┆ unit_group       │
│ ---    ┆ ---       ┆ ---                        ┆ ---              │
│ str    ┆ i64       ┆ str                        ┆ str              │
╞════════╪═══════════╪════════════════════════════╪══════════════════╡
│ angers ┆ 101       ┆ Cardiologie Angers         ┆ Cardiologie      │
│ angers ┆ 102       ┆ Urgences Angers            ┆ Urgences         │
│ angers ┆ 103       ┆ Pneumologie Angers         ┆ Pneumologie      │
│ angers ┆ 104       ┆ Médecine interne Angers    ┆ Médecine interne │
│ brest  ┆ 101       ┆ Cardiologie Brest          ┆ Cardiologie      │
│ …      ┆ …         ┆ …                          ┆ …                │
│ nantes ┆ 104       ┆ Médecine interne Nantes    ┆ Médecine interne │
│ tours  ┆ 101       ┆ Cardiologie Tours          ┆ Cardiologie      │
│ tours  ┆ 102       ┆ Urgences Tours             ┆ Urgences         │
│ tours  ┆ 104       ┆ Médecine interne Tours     ┆ Médecine interne │
│ tours  ┆ 105       ┆ Réanimation médicale Tours ┆ Réanimation      │
└────────┴───────────┴────────────────────────────┴──────────────────┘

In [7]:
stay = stay.with_columns(
    pl.col("unit_code").cast(pl.Utf8)
)

In [8]:
unit_mapping = unit_mapping.with_columns(
    pl.col("unit_code").cast(pl.Utf8)
)

In [9]:
stay.schema

Schema([('patient_id', String),
        ('centre', String),
        ('hosp_id', Int64),
        ('hosp_admission_datetime', Datetime(time_unit='us', time_zone=None)),
        ('hosp_discharge_datetime', Datetime(time_unit='us', time_zone=None)),
        ('stay_id', Int64),
        ('unit_code', String),
        ('unit_admission_datetime', Datetime(time_unit='us', time_zone=None)),
        ('unit_discharge_datetime', Datetime(time_unit='us', time_zone=None)),
        ('inclusion_flag', Int64)])

In [10]:
unit_mapping.schema

Schema([('centre', String),
        ('unit_code', String),
        ('unit_name', String),
        ('unit_group', String)])

In [11]:
unit_mapping.filter(pl.col("centre") == "brest")

shape: (3, 4)
┌────────┬───────────┬────────────────────────┬──────────────────┐
│ centre ┆ unit_code ┆ unit_name              ┆ unit_group       │
│ ---    ┆ ---       ┆ ---                    ┆ ---              │
│ str    ┆ str       ┆ str                    ┆ str              │
╞════════╪═══════════╪════════════════════════╪══════════════════╡
│ brest  ┆ 101       ┆ Cardiologie Brest      ┆ Cardiologie      │
│ brest  ┆ 103       ┆ Pneumologie Brest      ┆ Pneumologie      │
│ brest  ┆ 104       ┆ Médecine interne Brest ┆ Médecine interne │
└────────┴───────────┴────────────────────────┴──────────────────┘

In [12]:
unit_mapping.filter(pl.col("centre") == "angers")

shape: (4, 4)
┌────────┬───────────┬─────────────────────────┬──────────────────┐
│ centre ┆ unit_code ┆ unit_name               ┆ unit_group       │
│ ---    ┆ ---       ┆ ---                     ┆ ---              │
│ str    ┆ str       ┆ str                     ┆ str              │
╞════════╪═══════════╪═════════════════════════╪══════════════════╡
│ angers ┆ 101       ┆ Cardiologie Angers      ┆ Cardiologie      │
│ angers ┆ 102       ┆ Urgences Angers         ┆ Urgences         │
│ angers ┆ 103       ┆ Pneumologie Angers      ┆ Pneumologie      │
│ angers ┆ 104       ┆ Médecine interne Angers ┆ Médecine interne │
└────────┴───────────┴─────────────────────────┴──────────────────┘

In [13]:
unit_mapping.filter(pl.col("centre") == "tours")

shape: (4, 4)
┌────────┬───────────┬────────────────────────────┬──────────────────┐
│ centre ┆ unit_code ┆ unit_name                  ┆ unit_group       │
│ ---    ┆ ---       ┆ ---                        ┆ ---              │
│ str    ┆ str       ┆ str                        ┆ str              │
╞════════╪═══════════╪════════════════════════════╪══════════════════╡
│ tours  ┆ 101       ┆ Cardiologie Tours          ┆ Cardiologie      │
│ tours  ┆ 102       ┆ Urgences Tours             ┆ Urgences         │
│ tours  ┆ 104       ┆ Médecine interne Tours     ┆ Médecine interne │
│ tours  ┆ 105       ┆ Réanimation médicale Tours ┆ Réanimation      │
└────────┴───────────┴────────────────────────────┴──────────────────┘

In [14]:
unit_mapping.filter(pl.col("centre") == "nantes")

shape: (4, 4)
┌────────┬───────────┬─────────────────────────┬──────────────────┐
│ centre ┆ unit_code ┆ unit_name               ┆ unit_group       │
│ ---    ┆ ---       ┆ ---                     ┆ ---              │
│ str    ┆ str       ┆ str                     ┆ str              │
╞════════╪═══════════╪═════════════════════════╪══════════════════╡
│ nantes ┆ 101       ┆ Cardiologie Nantes      ┆ Cardiologie      │
│ nantes ┆ 102       ┆ Urgences Nantes         ┆ Urgences         │
│ nantes ┆ 103       ┆ Pneumologie Nantes      ┆ Pneumologie      │
│ nantes ┆ 104       ┆ Médecine interne Nantes ┆ Médecine interne │
└────────┴───────────┴─────────────────────────┴──────────────────┘

In [15]:
stay_with_units = stay.join(
    unit_mapping,
    on = ["centre", "unit_code"],
    how = "left"
)

In [16]:
stay_with_units

shape: (24, 12)
┌────────────┬────────┬─────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ patient_id ┆ centre ┆ hosp_id ┆ hosp_admis ┆ … ┆ unit_disch ┆ inclusion_ ┆ unit_name ┆ unit_grou │
│ ---        ┆ ---    ┆ ---     ┆ sion_datet ┆   ┆ arge_datet ┆ flag       ┆ ---       ┆ p         │
│ str        ┆ str    ┆ i64     ┆ ime        ┆   ┆ ime        ┆ ---        ┆ str       ┆ ---       │
│            ┆        ┆         ┆ ---        ┆   ┆ ---        ┆ i64        ┆           ┆ str       │
│            ┆        ┆         ┆ datetime[μ ┆   ┆ datetime[μ ┆            ┆           ┆           │
│            ┆        ┆         ┆ s]         ┆   ┆ s]         ┆            ┆           ┆           │
╞════════════╪════════╪═════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ P001       ┆ angers ┆ 1001    ┆ 2015-03-10 ┆ … ┆ 2015-03-16 ┆ 0          ┆ Cardiolog ┆ Cardiolog │
│            ┆        ┆         ┆ 09:30:00   ┆   ┆ 14:00:00   ┆            ┆ ie Angers ┆ ie        │
│ P001       ┆ angers ┆ 1002    ┆ 2018-07-04 ┆ … ┆ 2018-07-05 ┆ 1          ┆ Urgences  ┆ Urgences  │
│            ┆        ┆         ┆ 11:15:00   ┆   ┆ 10:00:00   ┆            ┆ Angers    ┆           │
│ P001       ┆ angers ┆ 1002    ┆ 2018-07-04 ┆ … ┆ 2018-07-12 ┆ 1          ┆ Pneumolog ┆ Pneumolog │
│            ┆        ┆         ┆ 11:15:00   ┆   ┆ 10:00:00   ┆            ┆ ie Angers ┆ ie        │
│ P002       ┆ brest  ┆ 2001    ┆ 2014-06-22 ┆ … ┆ 2014-06-28 ┆ 0          ┆ Médecine  ┆ Médecine  │
│            ┆        ┆         ┆ 08:40:00   ┆   ┆ 15:30:00   ┆            ┆ interne   ┆ interne   │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Brest     ┆           │
│ P002       ┆ brest  ┆ 2002    ┆ 2019-01-18 ┆ … ┆ 2019-01-25 ┆ 1          ┆ Pneumolog ┆ Pneumolog │
│            ┆        ┆         ┆ 13:20:00   ┆   ┆ 11:00:00   ┆            ┆ ie Brest  ┆ ie        │
│ …          ┆ …      ┆ …       ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ P008       ┆ tours  ┆ 8002    ┆ 2020-12-05 ┆ … ┆ 2020-12-20 ┆ 1          ┆ Réanimati ┆ Réanimati │
│            ┆        ┆         ┆ 06:45:00   ┆   ┆ 16:00:00   ┆            ┆ on        ┆ on        │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ médicale  ┆           │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Tours     ┆           │
│ P009       ┆ angers ┆ 9001    ┆ 2014-12-03 ┆ … ┆ 2014-12-09 ┆ 0          ┆ Cardiolog ┆ Cardiolog │
│            ┆        ┆         ┆ 10:15:00   ┆   ┆ 14:20:00   ┆            ┆ ie Angers ┆ ie        │
│ P009       ┆ angers ┆ 9002    ┆ 2017-01-26 ┆ … ┆ 2017-02-03 ┆ 1          ┆ Pneumolog ┆ Pneumolog │
│            ┆        ┆         ┆ 09:00:00   ┆   ┆ 11:45:00   ┆            ┆ ie Angers ┆ ie        │
│ P010       ┆ brest  ┆ 10001   ┆ 2015-04-18 ┆ … ┆ 2015-04-23 ┆ 0          ┆ Cardiolog ┆ Cardiolog │
│            ┆        ┆         ┆ 12:20:00   ┆   ┆ 10:00:00   ┆            ┆ ie Brest  ┆ ie        │
│ P010       ┆ brest  ┆ 10002   ┆ 2020-03-21 ┆ … ┆ 2020-04-02 ┆ 1          ┆ Pneumolog ┆ Pneumolog │
│            ┆        ┆         ┆ 16:30:00   ┆   ┆ 09:00:00   ┆            ┆ ie Brest  ┆ ie        │
└────────────┴────────┴─────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [17]:
import polars as pl
from datetime import datetime

document_data = pl.DataFrame({
    "patient_id": [
        "P001", "P001", "P001",
        "P002", "P002",
        "P003", "P003", "P003",
        "P004", "P004", "P004", "P004",
        "P005", "P005",
        "P006",
        "P008", "P008", "P008",
        "P010", "P010",
    ],

    "centre": [
        "angers", "angers", "angers",
        "brest", "brest",
        "nantes", "nantes", "nantes",
        "tours", "tours", "tours", "tours",
        "angers", "angers",
        "brest",
        "tours", "tours", "tours",
        "brest", "brest",
    ],

    "hosp_id": [
        1001, 1001, 1002,
        2001, 2002,
        3001, 3001, 3002,
        4001, 4002, 4002, 4002,
        5001, 5001,
        6002,
        8001, 8002, 8002,
        10001, 10002,
    ],

    "stay_id": [
        1, 1, 3,
        4, 5,
        6, 6, 7,
        10, 12, 12, 12,
        13, 13,
        16,
        18, 20, 20,
        23, 24,
    ],

    "document_data_id": [
        1, 2, 3,
        4, 5,
        6, 7, 8,
        9, 10, 11, 12,
        13, 14,
        15,
        16, 17, 18,
        19, 20,
    ],

    "terminology_code": [
        "CIM-10", "CIM-10", "CIM-10",
        "CIM-10", "CIM-10",
        "CIM-10", "CIM-10", "CIM-10",
        "CIM-10", "CIM-10", "CIM-10", "CCAM",
        "CIM-10", "CIM-10",
        "LOINC",
        "CIM-10", "CIM-10", "LOINC",
        "CIM-10", "CIM-10",
    ],

    "concept_code": [
        "I25", "I48", "J960",
        "E119", "J960",
        "I50", "N18", "J960",
        "I21", "I50", "Z950", "DEQP003",
        "C349", "E785",
        "14682-9",
        "I693", "J960", "2703-7",
        "I48", "J960",
    ],

    "concept_name": [
        "Cardiopathie ischémique chronique",
        "Fibrillation et flutter auriculaires",
        "Insuffisance respiratoire aiguë",

        "Diabète sucré de type 2 sans complication",
        "Insuffisance respiratoire aiguë",

        "Insuffisance cardiaque",
        "Insuffisance rénale chronique",
        "Insuffisance respiratoire aiguë",

        "Infarctus aigu du myocarde",
        "Insuffisance cardiaque",
        "Présence d'un stimulateur cardiaque électronique",
        "Échocardiographie transthoracique",

        "Cancer bronchique",
        "Hyperlipidémie, sans précision",

        "Créatinine",

        "Séquelles d'infarctus cérébral",
        "Insuffisance respiratoire aiguë",
        "Pression partielle en oxygène",

        "Fibrillation et flutter auriculaires",
        "Insuffisance respiratoire aiguë",
    ],

    "datetime": [
        datetime(2015, 3, 12, 10, 20),
        datetime(2015, 3, 12, 10, 25),
        datetime(2018, 7, 5, 11, 10),

        datetime(2014, 6, 23, 9, 30),
        datetime(2019, 1, 19, 10, 15),

        datetime(2016, 2, 6, 14, 0),
        datetime(2016, 2, 6, 14, 10),
        datetime(2019, 4, 10, 8, 45),

        datetime(2015, 11, 15, 16, 30),
        datetime(2018, 3, 5, 9, 20),
        datetime(2018, 3, 5, 9, 25),
        datetime(2018, 3, 6, 11, 0),

        datetime(2016, 8, 20, 10, 15),
        datetime(2016, 8, 20, 10, 20),

        datetime(2020, 6, 18, 7, 30),

        datetime(2017, 9, 11, 13, 40),
        datetime(2020, 12, 6, 9, 10),
        datetime(2020, 12, 6, 9, 30),

        datetime(2015, 4, 19, 9, 50),
        datetime(2020, 3, 22, 10, 10),
    ],

    "numeric_value": [
        None, None, None,
        None, None,
        None, None, None,
        None, None, None, None,
        None, None,
        142.0,
        None, None, 72.5,
        None, None,
    ],

    "text_value": [
        "DA", "DA", "DP",
        "DA", "DP",
        "DA", "DA", "DP",
        "DA", "DA", "DA", "Acte réalisé",
        "DA", "DA",
        None,
        "DA", "DP", None,
        "DA", "DP",
    ],

    "unit": [
        None, None, None,
        None, None,
        None, None, None,
        None, None, None, None,
        None, None,
        "µmol/L",
        None, None, "mmHg",
        None, None,
    ],
})

document_data

shape: (20, 12)
┌────────────┬────────┬─────────┬─────────┬───┬────────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime       ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---            ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]   ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪════════════════╪═══════════════╪════════════╪══════╡
│ P001       ┆ angers ┆ 1001    ┆ 1       ┆ … ┆ 2015-03-12     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:20:00       ┆               ┆            ┆      │
│ P001       ┆ angers ┆ 1001    ┆ 1       ┆ … ┆ 2015-03-12     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:25:00       ┆               ┆            ┆      │
│ P001       ┆ angers ┆ 1002    ┆ 3       ┆ … ┆ 2018-07-05     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 11:10:00       ┆               ┆            ┆      │
│ P002       ┆ brest  ┆ 2001    ┆ 4       ┆ … ┆ 2014-06-23     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:30:00       ┆               ┆            ┆      │
│ P002       ┆ brest  ┆ 2002    ┆ 5       ┆ … ┆ 2019-01-19     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:15:00       ┆               ┆            ┆      │
│ …          ┆ …      ┆ …       ┆ …       ┆ … ┆ …              ┆ …             ┆ …          ┆ …    │
│ P008       ┆ tours  ┆ 8001    ┆ 18      ┆ … ┆ 2017-09-11     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 13:40:00       ┆               ┆            ┆      │
│ P008       ┆ tours  ┆ 8002    ┆ 20      ┆ … ┆ 2020-12-06     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:10:00       ┆               ┆            ┆      │
│ P008       ┆ tours  ┆ 8002    ┆ 20      ┆ … ┆ 2020-12-06     ┆ 72.5          ┆ null       ┆ mmHg │
│            ┆        ┆         ┆         ┆   ┆ 09:30:00       ┆               ┆            ┆      │
│ P010       ┆ brest  ┆ 10001   ┆ 23      ┆ … ┆ 2015-04-19     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:50:00       ┆               ┆            ┆      │
│ P010       ┆ brest  ┆ 10002   ┆ 24      ┆ … ┆ 2020-03-22     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:10:00       ┆               ┆            ┆      │
└────────────┴────────┴─────────┴─────────┴───┴────────────────┴───────────────┴────────────┴──────┘

In [18]:
patient.write_parquet("patient.parquet")
stay.write_parquet("stay.parquet")
unit_mapping.write_parquet("unit_mapping.parquet")
document_data.write_parquet("document_data.parquet")

In [19]:
document_data.filter(pl.col("patient_id") == "P001")

shape: (3, 12)
┌────────────┬────────┬─────────┬─────────┬───┬────────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime       ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---            ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]   ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪════════════════╪═══════════════╪════════════╪══════╡
│ P001       ┆ angers ┆ 1001    ┆ 1       ┆ … ┆ 2015-03-12     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:20:00       ┆               ┆            ┆      │
│ P001       ┆ angers ┆ 1001    ┆ 1       ┆ … ┆ 2015-03-12     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:25:00       ┆               ┆            ┆      │
│ P001       ┆ angers ┆ 1002    ┆ 3       ┆ … ┆ 2018-07-05     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 11:10:00       ┆               ┆            ┆      │
└────────────┴────────┴─────────┴─────────┴───┴────────────────┴───────────────┴────────────┴──────┘

In [20]:
document_data.filter(pl.col("patient_id") == "P002")

shape: (2, 12)
┌────────────┬────────┬─────────┬─────────┬───┬────────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime       ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---            ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]   ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪════════════════╪═══════════════╪════════════╪══════╡
│ P002       ┆ brest  ┆ 2001    ┆ 4       ┆ … ┆ 2014-06-23     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:30:00       ┆               ┆            ┆      │
│ P002       ┆ brest  ┆ 2002    ┆ 5       ┆ … ┆ 2019-01-19     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:15:00       ┆               ┆            ┆      │
└────────────┴────────┴─────────┴─────────┴───┴────────────────┴───────────────┴────────────┴──────┘

In [21]:
document_data.filter(pl.col("patient_id") == "P003")

shape: (3, 12)
┌────────────┬────────┬─────────┬─────────┬───┬────────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime       ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---            ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]   ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪════════════════╪═══════════════╪════════════╪══════╡
│ P003       ┆ nantes ┆ 3001    ┆ 6       ┆ … ┆ 2016-02-06     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 14:00:00       ┆               ┆            ┆      │
│ P003       ┆ nantes ┆ 3001    ┆ 6       ┆ … ┆ 2016-02-06     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 14:10:00       ┆               ┆            ┆      │
│ P003       ┆ nantes ┆ 3002    ┆ 7       ┆ … ┆ 2019-04-10     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 08:45:00       ┆               ┆            ┆      │
└────────────┴────────┴─────────┴─────────┴───┴────────────────┴───────────────┴────────────┴──────┘

In [22]:
document_data.filter(pl.col("patient_id") == "P004")

shape: (4, 12)
┌────────────┬────────┬─────────┬─────────┬───┬───────────────┬──────────────┬──────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime      ┆ numeric_valu ┆ text_value   ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---           ┆ e            ┆ ---          ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]  ┆ ---          ┆ str          ┆ str  │
│            ┆        ┆         ┆         ┆   ┆               ┆ f64          ┆              ┆      │
╞════════════╪════════╪═════════╪═════════╪═══╪═══════════════╪══════════════╪══════════════╪══════╡
│ P004       ┆ tours  ┆ 4001    ┆ 10      ┆ … ┆ 2015-11-15    ┆ null         ┆ DA           ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 16:30:00      ┆              ┆              ┆      │
│ P004       ┆ tours  ┆ 4002    ┆ 12      ┆ … ┆ 2018-03-05    ┆ null         ┆ DA           ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:20:00      ┆              ┆              ┆      │
│ P004       ┆ tours  ┆ 4002    ┆ 12      ┆ … ┆ 2018-03-05    ┆ null         ┆ DA           ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:25:00      ┆              ┆              ┆      │
│ P004       ┆ tours  ┆ 4002    ┆ 12      ┆ … ┆ 2018-03-06    ┆ null         ┆ Acte réalisé ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 11:00:00      ┆              ┆              ┆      │
└────────────┴────────┴─────────┴─────────┴───┴───────────────┴──────────────┴──────────────┴──────┘

In [23]:
document_data.filter(pl.col("patient_id") == "P005")

shape: (2, 12)
┌────────────┬────────┬─────────┬─────────┬───┬────────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime       ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---            ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]   ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪════════════════╪═══════════════╪════════════╪══════╡
│ P005       ┆ angers ┆ 5001    ┆ 13      ┆ … ┆ 2016-08-20     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:15:00       ┆               ┆            ┆      │
│ P005       ┆ angers ┆ 5001    ┆ 13      ┆ … ┆ 2016-08-20     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:20:00       ┆               ┆            ┆      │
└────────────┴────────┴─────────┴─────────┴───┴────────────────┴───────────────┴────────────┴──────┘

In [24]:
document_data.filter(pl.col("patient_id") == "P006")

shape: (1, 12)
┌────────────┬────────┬─────────┬─────────┬───┬───────────────┬──────────────┬────────────┬────────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime      ┆ numeric_valu ┆ text_value ┆ unit   │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---           ┆ e            ┆ ---        ┆ ---    │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]  ┆ ---          ┆ str        ┆ str    │
│            ┆        ┆         ┆         ┆   ┆               ┆ f64          ┆            ┆        │
╞════════════╪════════╪═════════╪═════════╪═══╪═══════════════╪══════════════╪════════════╪════════╡
│ P006       ┆ brest  ┆ 6002    ┆ 16      ┆ … ┆ 2020-06-18    ┆ 142.0        ┆ null       ┆ µmol/L │
│            ┆        ┆         ┆         ┆   ┆ 07:30:00      ┆              ┆            ┆        │
└────────────┴────────┴─────────┴─────────┴───┴───────────────┴──────────────┴────────────┴────────┘

In [25]:
document_data.filter(pl.col("patient_id") == "P007")

shape: (0, 12)
┌────────────┬────────┬─────────┬─────────┬───┬──────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime     ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---          ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs] ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪══════════════╪═══════════════╪════════════╪══════╡
└────────────┴────────┴─────────┴─────────┴───┴──────────────┴───────────────┴────────────┴──────┘

In [26]:
document_data.filter(pl.col("patient_id") == "P008")

shape: (3, 12)
┌────────────┬────────┬─────────┬─────────┬───┬────────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime       ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---            ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]   ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪════════════════╪═══════════════╪════════════╪══════╡
│ P008       ┆ tours  ┆ 8001    ┆ 18      ┆ … ┆ 2017-09-11     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 13:40:00       ┆               ┆            ┆      │
│ P008       ┆ tours  ┆ 8002    ┆ 20      ┆ … ┆ 2020-12-06     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:10:00       ┆               ┆            ┆      │
│ P008       ┆ tours  ┆ 8002    ┆ 20      ┆ … ┆ 2020-12-06     ┆ 72.5          ┆ null       ┆ mmHg │
│            ┆        ┆         ┆         ┆   ┆ 09:30:00       ┆               ┆            ┆      │
└────────────┴────────┴─────────┴─────────┴───┴────────────────┴───────────────┴────────────┴──────┘

In [27]:
document_data.filter(pl.col("patient_id") == "P009")

shape: (0, 12)
┌────────────┬────────┬─────────┬─────────┬───┬──────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime     ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---          ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs] ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪══════════════╪═══════════════╪════════════╪══════╡
└────────────┴────────┴─────────┴─────────┴───┴──────────────┴───────────────┴────────────┴──────┘

In [28]:
document_data.filter(pl.col("patient_id") == "P010")

shape: (2, 12)
┌────────────┬────────┬─────────┬─────────┬───┬────────────────┬───────────────┬────────────┬──────┐
│ patient_id ┆ centre ┆ hosp_id ┆ stay_id ┆ … ┆ datetime       ┆ numeric_value ┆ text_value ┆ unit │
│ ---        ┆ ---    ┆ ---     ┆ ---     ┆   ┆ ---            ┆ ---           ┆ ---        ┆ ---  │
│ str        ┆ str    ┆ i64     ┆ i64     ┆   ┆ datetime[μs]   ┆ f64           ┆ str        ┆ str  │
╞════════════╪════════╪═════════╪═════════╪═══╪════════════════╪═══════════════╪════════════╪══════╡
│ P010       ┆ brest  ┆ 10001   ┆ 23      ┆ … ┆ 2015-04-19     ┆ null          ┆ DA         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 09:50:00       ┆               ┆            ┆      │
│ P010       ┆ brest  ┆ 10002   ┆ 24      ┆ … ┆ 2020-03-22     ┆ null          ┆ DP         ┆ null │
│            ┆        ┆         ┆         ┆   ┆ 10:10:00       ┆               ┆            ┆      │
└────────────┴────────┴─────────┴─────────┴───┴────────────────┴───────────────┴────────────┴──────┘

In [29]:
import polars as pl

drug_data = pl.DataFrame({
    "ent_id": [
        "D001", "D002",
        "D003",
        "D004", "D005", "D006",
        "D007", "D008", "D009",
        "D010",
        "D011", "D012",
        "D013",
    ],

    # context_id can represent the hospital stay context
    # Here I use hosp_id from the stay table
    "context_id": [
        "1001", "1001",
        "2001",
        "3001", "3001", "3001",
        "4001", "4002", "4002",
        "6002",
        "8001", "8002",
        "10001",
    ],

    # synthetic text document identifiers
    "text_id": [
        "TXT001", "TXT001",
        "TXT002",
        "TXT003", "TXT003", "TXT003",
        "TXT004", "TXT005", "TXT005",
        "TXT006",
        "TXT007", "TXT008",
        "TXT009",
    ],

    "patient_id": [
        "P001", "P001",
        "P002",
        "P003", "P003", "P003",
        "P004", "P004", "P004",
        "P006",
        "P008", "P008",
        "P010",
    ],

    "context_type": [
        "hospitalisation", "hospitalisation",
        "hospitalisation",
        "hospitalisation", "hospitalisation", "hospitalisation",
        "hospitalisation", "hospitalisation", "hospitalisation",
        "hospitalisation",
        "hospitalisation", "hospitalisation",
        "hospitalisation",
    ],

    "ent_name": [
        "bisoprolol",
        "ramipril",

        "metformine",

        "bisoprolol",
        "furosémide",
        "spironolactone",

        "bisoprolol",
        "sacubitril valsartan",
        "dapagliflozine",

        "paracétamol",

        "atorvastatine",
        "apixaban",

        "amiodarone",
    ],

    # ATC codes when available
    "code_atc": [
        "C07AB07",   # bisoprolol: beta-blocker
        "C09AA05",   # ramipril: ACE inhibitor

        "A10BA02",   # metformin

        "C07AB07",   # bisoprolol
        "C03CA01",   # furosemide
        "C03DA01",   # spironolactone

        "C07AB07",   # bisoprolol
        "C09DX04",   # sacubitril/valsartan: ARNI
        "A10BK01",   # dapagliflozin: SGLT2 inhibitor

        "N02BE01",   # paracetamol

        "C10AA05",   # atorvastatin
        "B01AF02",   # apixaban

        "C01BD01",   # amiodarone
    ],

    # UCD codes are synthetic here
    "code_ucd": [
        "UCD001", "UCD002",
        "UCD003",
        "UCD001", "UCD004", "UCD005",
        "UCD001", "UCD006", "UCD007",
        "UCD008",
        "UCD009", "UCD010",
        "UCD011",
    ],

    # List(String), as in your schema
    "dose": [
        ["2.5 mg"],
        ["5 mg"],

        ["500 mg"],

        ["1.25 mg"],
        ["40 mg"],
        ["25 mg"],

        ["2.5 mg"],
        ["24/26 mg"],
        ["10 mg"],

        ["1 g"],

        ["20 mg"],
        ["5 mg"],

        ["200 mg"],
    ],

    # List(String), as in your schema
    "frequency/duration": [
        ["1 fois/jour"],
        ["1 fois/jour"],

        ["2 fois/jour"],

        ["1 fois/jour"],
        ["1 fois/jour"],
        ["1 fois/jour"],

        ["1 fois/jour"],
        ["2 fois/jour"],
        ["1 fois/jour"],

        ["si besoin"],

        ["1 fois/jour"],
        ["2 fois/jour"],

        ["1 fois/jour"],
    ],

    # synthetic start/end dates encoded as integers
    # You can later replace these by real dates if needed
    "ent_start": [
        20150310, 20150310,
        20140622,
        20160205, 20160205, 20160205,
        20151114, 20180303, 20180303,
        20200617,
        20170910, 20201205,
        20150418,
    ],

    "ent_end": [
        20150316, 20150316,
        20140628,
        20160211, 20160211, 20160211,
        20151120, 20180318, 20180318,
        20200624,
        20170916, 20201220,
        20150423,
    ],
})

drug_data

shape: (13, 12)
┌────────┬────────────┬─────────┬────────────┬───┬─────────────┬────────────┬───────────┬──────────┐
│ ent_id ┆ context_id ┆ text_id ┆ patient_id ┆ … ┆ dose        ┆ frequency/ ┆ ent_start ┆ ent_end  │
│ ---    ┆ ---        ┆ ---     ┆ ---        ┆   ┆ ---         ┆ duration   ┆ ---       ┆ ---      │
│ str    ┆ str        ┆ str     ┆ str        ┆   ┆ list[str]   ┆ ---        ┆ i64       ┆ i64      │
│        ┆            ┆         ┆            ┆   ┆             ┆ list[str]  ┆           ┆          │
╞════════╪════════════╪═════════╪════════════╪═══╪═════════════╪════════════╪═══════════╪══════════╡
│ D001   ┆ 1001       ┆ TXT001  ┆ P001       ┆ … ┆ ["2.5 mg"]  ┆ ["1 fois/j ┆ 20150310  ┆ 20150316 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ D002   ┆ 1001       ┆ TXT001  ┆ P001       ┆ … ┆ ["5 mg"]    ┆ ["1 fois/j ┆ 20150310  ┆ 20150316 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ D003   ┆ 2001       ┆ TXT002  ┆ P002       ┆ … ┆ ["500 mg"]  ┆ ["2 fois/j ┆ 20140622  ┆ 20140628 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ D004   ┆ 3001       ┆ TXT003  ┆ P003       ┆ … ┆ ["1.25 mg"] ┆ ["1 fois/j ┆ 20160205  ┆ 20160211 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ D005   ┆ 3001       ┆ TXT003  ┆ P003       ┆ … ┆ ["40 mg"]   ┆ ["1 fois/j ┆ 20160205  ┆ 20160211 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ …      ┆ …          ┆ …       ┆ …          ┆ … ┆ …           ┆ …          ┆ …         ┆ …        │
│ D009   ┆ 4002       ┆ TXT005  ┆ P004       ┆ … ┆ ["10 mg"]   ┆ ["1 fois/j ┆ 20180303  ┆ 20180318 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ D010   ┆ 6002       ┆ TXT006  ┆ P006       ┆ … ┆ ["1 g"]     ┆ ["si       ┆ 20200617  ┆ 20200624 │
│        ┆            ┆         ┆            ┆   ┆             ┆ besoin"]   ┆           ┆          │
│ D011   ┆ 8001       ┆ TXT007  ┆ P008       ┆ … ┆ ["20 mg"]   ┆ ["1 fois/j ┆ 20170910  ┆ 20170916 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ D012   ┆ 8002       ┆ TXT008  ┆ P008       ┆ … ┆ ["5 mg"]    ┆ ["2 fois/j ┆ 20201205  ┆ 20201220 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
│ D013   ┆ 10001      ┆ TXT009  ┆ P010       ┆ … ┆ ["200 mg"]  ┆ ["1 fois/j ┆ 20150418  ┆ 20150423 │
│        ┆            ┆         ┆            ┆   ┆             ┆ our"]      ┆           ┆          │
└────────┴────────────┴─────────┴────────────┴───┴─────────────┴────────────┴───────────┴──────────┘

In [30]:
drug_data.join(
    patient.select("patient_id"),
    on="patient_id",
    how="anti"
)

shape: (0, 12)
┌────────┬────────────┬─────────┬────────────┬───┬───────────┬───────────────┬───────────┬─────────┐
│ ent_id ┆ context_id ┆ text_id ┆ patient_id ┆ … ┆ dose      ┆ frequency/dur ┆ ent_start ┆ ent_end │
│ ---    ┆ ---        ┆ ---     ┆ ---        ┆   ┆ ---       ┆ ation         ┆ ---       ┆ ---     │
│ str    ┆ str        ┆ str     ┆ str        ┆   ┆ list[str] ┆ ---           ┆ i64       ┆ i64     │
│        ┆            ┆         ┆            ┆   ┆           ┆ list[str]     ┆           ┆         │
╞════════╪════════════╪═════════╪════════════╪═══╪═══════════╪═══════════════╪═══════════╪═════════╡
└────────┴────────────┴─────────┴────────────┴───┴───────────┴───────────────┴───────────┴─────────┘

In [31]:
patient.select("patient_id").join(
    drug_data.select("patient_id").unique(),
    on="patient_id",
    how="anti"
)

shape: (3, 1)
┌────────────┐
│ patient_id │
│ ---        │
│ str        │
╞════════════╡
│ P005       │
│ P007       │
│ P009       │
└────────────┘

In [32]:
drug_data.write_parquet("traitement.parquet")